### ISSUE TITLE
ModuleNotFoundError: No module named 'xdg.BaseDirectory'

### ISSUE THREAD

**Issue by jothi-prasath** [Ladbaby/lastfm-scrobbler#1]
Archlinux installed using pip

* i face this error
![image](https://github.com/Ladbaby/lastfm-scrobbler/assets/64248628/506fdff1-0b95-4f04-a478-891d98151961)

* then i installed "xdg" then it shows like this
![image](https://github.com/Ladbaby/lastfm-scrobbler/assets/64248628/cb3191fd-4168-4f3c-ba54-9785be35bd88)

**Comment by Ladbaby** [comment]
Did you run `pip install pyxdg`? It seems that I overlooked this dependency when uploaded to pypi

**Comment by jothi-prasath** [comment]
i installed `pip install pyxdg` 

![image](https://github.com/Ladbaby/lastfm-scrobbler/assets/64248628/be5c0f88-31e9-48f3-b0a1-b9bc6248e214)

**Comment by Ladbaby** [comment]
The program needs a command line argument to work like `lastfm-mpris2-scrobbler -c PATH_TO_YOUR_CONFIG/config.yaml`, for more information on how to use it, you may refer to the [Usage](https://github.com/Ladbaby/lastfm-scrobbler/blob/main/README.md#Usage) section of README, also on how to write the config file at [Configurations](https://github.com/Ladbaby/lastfm-scrobbler/blob/main/README.md#Configurations) section

**Comment by jothi-prasath** [comment]
thanks ❤️

**Comment by grimmy** [comment]
Any reason pyxdg isn't in `requirements.txt` or `setup.py`? I ran into the same issue after cloning and installing into a virtualenv and luckily found this issue because the top results for xdg on pypi didn't seem to fix the issue...

**Comment by Ladbaby** [comment]
> Any reason pyxdg isn't in `requirements.txt` or `setup.py`? I ran into the same issue after cloning and installing into a virtualenv and luckily found this issue because the top results for xdg on pypi didn't seem to fix the issue...

Sorry for the confusion, it's my mistake when packing it. I'm now busy working on other stuff and haven't got time to update it
