### ISSUE TITLE
Feature: Add config option for played for 

### ISSUE THREAD

**Issue by bonelifer** [Ladbaby/lastfm-scrobbler#2]
Add config option for played for, so it can be changed without messing with the code.

**Comment by Ladbaby** [comment]
The current setting is based on last.fm's defaults, but I do think it better to have a config option. Will change it when I get spare time

**Comment by Ladbaby** [comment]
My dual-boot Linux seems to be broken and cannot use for now, the feature has to be postponed...

**Comment by Ladbaby** [comment]
The new release v1.0.3 is available now with the new config option for scrobble time threshold. Remember to update the config file too.
