### ISSUE TITLE
Failed to retrieve key='xesam:firstUsed' from player. Value for this key is set to default

### ISSUE THREAD

**Issue by Nekothegamer** [Ladbaby/lastfm-scrobbler#4]
i get this issue when i set up the scrobbler configuration. what does it mean, and how can i solve it?

**Comment by Ladbaby** [comment]
It would normally be safe to ignore this warning message, meaning the track does not have the `firstUsed` attribute, which does not affect the scrobbling result in my understanding. You can filter out this message by changing the app's log level in the config file:
```yaml
log_level: INFO
```
then restart the program.

**Comment by Nekothegamer** [comment]
ok... but the scrobbler still doesn't scrobble anything, even if a song does go over the threshold

does that mean that the player i'm using is incompatible then?

**Comment by Ladbaby** [comment]
I'm sorry to hear that. Can you provide all the logs until it went over the time threshold (with log_level set to DEBUG) and also the music player you are using? I have met similar situation before as mentioned in "Known Issues" in README, which is caused by some unwanted substring (e.g., `.mp3`) in music's title (e.g., the title is `music_title.mp3` instead of `music_title`). Last.fm seems to reject incorrect music title.

**Comment by Nekothegamer** [comment]
This is weird: i changed `log_level` in `DEBUG` in the `config.yaml` and now this is the output

![immagine](https://github.com/user-attachments/assets/5e8e20c4-052b-4e3d-b901-fce02f752e14)

only this, there's nothing more afterwards

btw the player i'm attempting to use is [GNOME Music](https://apps.gnome.org/Music)

**Comment by popey** [comment]
FWIW I just installed GNOME Music on my Ubuntu 24.04 system and it successfully scrobbled two tracks I just heard. First scrobble for four years, just to comment on this issue. :D 

```log
2024-08-20 19:55:36 PrecisePad dbus-scrobbler[1235256] INFO scrobbled: [{'artist': 'Arctic Monkeys', 'title': 'Do I Wanna Know?', 'timestamp': 1724180136, 'album': 'AM', 'album_artist': 'Arctic Monkeys', 'track_number': 1, 'duration': 272}]
2024-08-20 19:59:40 PrecisePad dbus-scrobbler[1235256] INFO scrobbled: [{'artist': 'Arctic Monkeys', 'title': 'R U Mine?', 'timestamp': 1724180379, 'album': 'AM', 'album_artist': 'Arctic Monkeys', 'track_number': 2, 'duration': 201}]
```

GNOME Music 46.0-1build1

```
application_whitelist: [ "org.mpris.MediaPlayer2.spotify" , "org.mpris.MediaPlayer2.org.gnome.Music" ]
```

**Comment by Nekothegamer** [comment]
**wait**

let me try something...

**Comment by Nekothegamer** [comment]
YESSS!!!!! I found out why it didn't scrobble!!

i literally just had to put the app i wanted to use in the whitelist, and now it's scrobbling tracks!!!!!!! 

minus the `Failed to retrieve key='xesam:firstUsed' from player. Value for this key is set to default`, `Failed to retrieve key='xesam:discNumber' from player. Value for this key is set to default` and `Failed to retrieve key='xesam:trackNumber' from player. Value for this key is set to default`, but as Lad said those are easily ignorable, and in fact i can just turn them off with that `log_level` parameter on the config file

thank you so much @popey for making me realize the issue, i wouldn't have gone nowhere if you didn't show your testing!!!

**Comment by Nekothegamer** [comment]
and after this, i can surely close the issue as i can definitely agree it's been solved

**Comment by Nekothegamer** [comment]
to be honest i'm so stupid for not thinking about this earlier, as it was *literally* written on the config file all along

**Comment by Ladbaby** [comment]
Thanks @popey for providing extra information, and I'm glad to hear the problem has been solved :)
